# Generated by Django 5.2.5 on 2025-08-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_avatar",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
