# Generated by Django 5.2.5 on 2025-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="like",
            name="is_dislike",
            field=models.BooleanField(default=False),
        ),
    ]
