# Generated by Django 5.2.5 on 2025-08-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_like_is_dislike"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="is_dislike",
            new_name="is_disliked",
        ),
    ]
