# Generated by Django 5.2.5 on 2025-08-21 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_is_dislike_like_is_disliked"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("author", "post"), name="unique_like_per_user_post"
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("author", "comment"), name="unique_like_per_user_comment"
            ),
        ),
    ]
